{
 "title": "Alentapp RED Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Porcentaje de Errores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_count{http_status_code=~\"[45]..\"}[5m])) / sum(rate(http_server_duration_count[5m]))) * 100 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasa de Tráfico Actual (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia del Percentil 95 (Duration)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribución de Respuestas por Código HTTP",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count[5m])) by (http_status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo de Memoria RAM del Contenedor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "v8js_memory_heap_used / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 de Endpoints más lentos",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(http_server_duration_sum[5m])) by (http_route) / sum(rate(http_server_duration_count[5m])) by (http_route))",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 de Endpoints más lentos",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "topk(5, avg by (http_route) (rate(http_server_duration_sum[5m]) / rate(http_server_duration_count[5m])))",
       "legendFormat": "{{http_route}}"
      }
     ]
    },
    {
     "title": "Top 5 de Endpoints más lentos",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "topk(5, avg by (http_method) (rate(http_server_duration_sum[5m]) / rate(http_server_duration_count[5m])))",
       "legendFormat": "{{http_method}}"
      }
     ]
    },
    {
     "title": "Top 5 de Endpoints más lentos",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "targets": [
      { "expr": "http_server_duration_count", "legendFormat": "{{route}}" }
     ]
    },
    {
     "title": "Consumo de Memoria RAM del Contenedor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "process_memory_nodejs_usage_bytes{type=\"heapUsed\"} / 1024 / 1024",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}